### ISSUE TITLE
Deck openapi2kong regex_priority forcing unsigned int

### ISSUE THREAD

**Issue by deckong** [Kong/go-apiops#158]
When using deck v1.35 and looking to convert an openapi file with the command `deck openapi2kong file-name.yaml`

The regex_priority when set to a negative number, will become a very large integer on a path given that that path has regex within it. For example if I have a path of /test/{tester} and it has a regex_priority of -10, the converted file output will look like the following: `regex_priority: 18446744073709551605`

This seems to be the max size of unsigned int minus 10. 

The code snippet I believe is this here: https://github.com/Kong/go-apiops/blob/05ef8ef2321deaf33684e7bd9b2881c3047a9ece/openapi2kong/openapi2kong.go#L1104-L1106

This can be replicated with the file attached and using the command `deck file openapi2kong -s openapi.yml `

[openapi.txt](https://github.com/Kong/go-apiops/files/14529224/openapi.txt)

**Comment by Tieske** [comment]
I think the problem is here: https://github.com/Kong/go-apiops/blob/05ef8ef2321deaf33684e7bd9b2881c3047a9ece/openapi2kong/openapi2kong.go#L1099

That's where the result is cast to a UINT

**Comment by Tieske** [comment]
fix released in decK 1.36.2
