### ISSUE TITLE
`deck file patch` with path lengths > 128 characters

### ISSUE THREAD

**Issue by mheap** [Kong/go-apiops#198]
Running `deck file patch` on an OpenAPI spec where the path is > 128 characters in length throws an error:

```
# deck file patch -s simple20.yaml -o output20.yaml --selector=$..info --value='version:"2.2.0"' --verbose 2

2024/06/03 11:24:42 "level"=2 "msg"="parsed patch-instruction" "key"="version" "value"="2.2.0"

2024/06/03 11:24:42 "level"=2 "msg"="applying value-flags"
panic: invalid character '?' looking for beginning of object key string

goroutine 1 [running]:
github.com/kong/go-apiops/jsonbasics.ConvertToJSONInterface(0x101364468?)
github.com/kong/go-apiops@v0.1.29/jsonbasics/jsonbasics.go:340 +0x90
github.com/kong/go-apiops/jsonbasics.ConvertToJSONobject(0x14000619bf0?)
github.com/kong/go-apiops@v0.1.29/jsonbasics/jsonbasics.go:346 +0x1c
github.com/kong/deck/cmd.executePatch(0x140004a2c00?, {0x14000461100?, 0x0, 0x8})
github.com/kong/deck/cmd/file_patch.go:102 +0x8b0
github.com/spf13/cobra.(*Command).execute(0x140004bf800, {0x14000461080, 0x8, 0x8})
github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x14000442000)
github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(...)
github.com/spf13/cobra@v1.8.0/command.go:1032
github.com/kong/deck/cmd.Execute({0x1013615e0?, 0x14000393db0})
github.com/kong/deck/cmd/root.go:264 +0x68
main.main()
github.com/kong/deck/main.go:31 +0x20
```

Related GH issues:

https://github.com/go-yaml/yaml/pull/1031
https://github.com/go-yaml/yaml/issues/849

Proposed resolution: Fork `go-yaml` and use our own fork until the upstream PR is accepted

**Comment by Tieske** [comment]
proposed fix: https://github.com/go-yaml/yaml/pull/1037

**Comment by Prashansa-K** [comment]
> Running deck file patch on an OpenAPI spec where the path is > 128 characters in length throws an error:
@mheap Could you please clarify what we mean by "path" here?

**Comment by Prashansa-K** [comment]
@Tieske On merging the changes you suggested [here](https://github.com/go-yaml/yaml/pull/1037) in our own fork, we don't get errors anymore in case any path in OpenAPI spec >128 chars, but the rendered yaml doesn't consider the "path with len >128 chars" as a simple key. We get a complex key - complex value mapping in the output post a `deck file patch`. Adding SS (notice the `?` before pathname and `:` before value get:
![Image](https://github.com/user-attachments/assets/dcf54afa-64cb-4fe8-8293-90e4c7028192)

Note: The rendered spec is still valid, just the path key isn't treated as simple anymore.
I just want to clarify if that is something we are okay with in deck output. @mheap 
In my opinion, this shouldn't be a blocker as the spec and the yaml remains valid, but I wanted to know your opinion.

**Comment by Tieske** [comment]
I do not follow. The example is an OAS file, so that is the input to deck, correct? so where do we create this file, if it was written by deck?

**Comment by Prashansa-K** [comment]
Okay. The above SS showed the output.

Here's the input SS. Path is of 145 chars.
![Image](https://github.com/user-attachments/assets/63d4ec1b-ce67-4774-81a8-266cf234df6c)

On running `deck file patch -s test.yaml -o output20.yaml --selector=$..info --value='version:"2.2.0"'`, we don't get any errors. The output file is generated properly with valid yaml. I was just pointing out that in the output file, the 145 char path becomes a complex yaml key-value pair.

![Image](https://github.com/user-attachments/assets/4763e9a4-93da-4c99-86f2-d299ae0869eb)
The yaml is valid and can be fed to the `deck file patch` command again.

**Comment by Prashansa-K** [comment]
@mheap I had a word with Thijs about the yaml output changes. The generated yaml (with complex key mapping) works fine with other deck commands like patch, openapi2kong, etc. and a subsequent deck sync works fine as well.
Let us know if we still need to do something about the complex key change or document it out somewhere. To be fair, it is not a behaviour change, as the yaml is valid and works with the rest of the stuff, it is more of a visualisation change.

To clarify: the complex key yaml output shows up only if the path length is >128 characters. Otherwise, the output is a simple key mapping (as earlier).

**Comment by mheap** [comment]
No changes needed elsewhere. Please ship the fix
