### ISSUE TITLE
Add switch to disable command history

### ISSUE THREAD

**Issue by rspurgeon** [Kong/go-apiops#37]
Command history populates a file with a pipeline of commands ran. For example:

```
- command: merge
  files:
  - filename: .github/artifacts/kong/flight-data-flights-kong.yaml
    info:
    - command: openapi2kong
      input: flight-data/flights/openapi.yaml
      output: .github/artifacts/kong/flight-data-flights-kong.yaml
      uuid-base: ""
      version: kceD v0.1.11 (347b296)
```

One issue here is that multiple runs with different versions of the tool will result in different results. Thus, subsequent runs with no changes (other then the version of the tool ran) will result in non-idempotent results.  This could trigger downstream processes unnecessarily (including deployment to Kong).

**Comment by rspurgeon** [comment]
Either we add a switch or make the command history opt-in instead of opt-out

**Comment by Tieske** [comment]
maybe just reduce cardinality; drop the `version` all together, and change `command` to `kced openapi2kong`
