### ISSUE TITLE
_ignore with command history not compatible with deck v1.19.1

### ISSUE THREAD

**Issue by rspurgeon** [Kong/go-apiops#39]
When running our generated files with the command history feature, deck errors that the _ignore property is not allowed.  For example:

```
deck diff -s platform/kong-combined.yaml --konnect-runtime-group-name default --konnect-token $KONNECT_PAT
Error: reading file: validating file content: 1 errors occurred:
        (root): Additional property _ignore is not allowed
```

If I remove the entire `_ignore` key, then the file is processed as expected.

**Comment by Tieske** [comment]
That’s a deck bug.

**Comment by Tieske** [comment]
as a workaround, the `patch` command can be used to remove the history;

```
kced patch --selector "$" --value "_ignore:"
```

**Comment by Tieske** [comment]
begs the question; if this needs a deck fix, should we update the key at the same time? so instead of abusing "_ignore" (which was temporary anyway), we introduce something like "_history" ?

**Comment by rspurgeon** [comment]
As discussed, we should remove this feature until `deck` has proper support for "ignored" annotations in the file.  Otherwise we are building invalid deck files based on the current deck behavior.

I agree, we should have a discussion w/ the deck team on a better way to support this.
