### ISSUE TITLE
Add alias oas2kong for command openapi2kong

### ISSUE THREAD

**Issue by rspurgeon** [Kong/go-apiops#48]
The Kong inso tool uses the shorter version of the command.  To help support a migration path, add an alias for the `oas2kong` version of the same command.

**Comment by Tieske** [comment]
Since `kced` is temporary, the main question is what the command is going to be in the final `decK` cli. Then we can just switch to that.

**Comment by rspurgeon** [comment]
Since Cobra supports aliases, IMO we could just cover both in `kced` and `deck`.

**Comment by Tieske** [comment]
superseded by later discussions on CLI. closing this.
