### ISSUE TITLE
Deck file merge - Entity already exists

### ISSUE THREAD

**Issue by cfw-cagip** [Kong/go-apiops#84]
Hi Guys,

I am setting up a gitlab ci pipeline that will allow publishing apis in kong. The error message is Error: building state: inserting route Swagger_Petstore-listPets: entity already exists.

In my pipeline, I have to convert an openapi (oas) specification to a kong specification (this is done with the command deck file openapi2kong -s oas.yaml -o kong-spec.yaml).
Then I make a backup of the current Kong configuration (deck dump -o current-spec.yaml) and I merge current-spec.yaml and kong-spec.yaml files to get the final file to synchronize on kong (deck file merge current-spec.yaml kong-spec.yaml -o merge-spec.yaml).

At the first occurrence of publication, it goes without a hitch. (deck diff -s merge-spec.yaml; deck sync -s merge-spec.yaml). On the other hand for all other occurrences of file merge, it does not work since the elements defining the api some already exist in kong.

So with the deck tool is it possible to do a file merge by solving the problem of duplication and prioritizing the specification to keep according to its position in the list of files provided as a parameter to deck.

Deck version : v1.25.0
Kong version : v3.2

Thanks in advance

**Comment by Tieske** [comment]
The `merge` command will merge files into a single file, but it will not validate whether the result is a valid Kong declarative file. Hence the failure at sync time.

Your approach is not how it is intended. There should be no need to first dump the config. If your file is really declarative, then the entire config is in the file no? and hence you should be able to overwrite the existing config.

Now if you have other configs in the Kong system you need to sync to, then I suggest you use tags to identify what to sync to. The OpenAPI conversion can be given tags (or they can be added later by add-tags), and when syncing provide the "--select-tags" to select the netities in the current Kong to sync against.

**Comment by Tieske** [comment]
Closing this. If you need more help, let us know or reopen.
