### ISSUE TITLE
Minor documentation issue in learn service OAS yaml example

### ISSUE THREAD

**Issue by rspurgeon** [Kong/go-apiops#94]
https://github.com/Kong/go-apiops/blob/cd3a7f217d4a711c4f1b3ffa5a817e738268d2fa/docs/learnservice_oas.yaml#L128C46-L128C66

documents the eventual name as `"awesome-learnservice-upserttracks"` but the name in `x-kong-name` at the top is `awesome_learnservice`

**Comment by Tieske** [comment]
Need to run another test to check another edge case (regex), will fix when doing that
