### ISSUE TITLE
Kong 2.x compatibility with openapi2kong

### ISSUE THREAD

**Issue by danielpoonwj** [Kong/go-apiops#98]
Hi!

There is an incompatibility with Kong 2.x for the generated routes. When running `deck validate --online`, there's this error
```
validate entity 'routes (<redacted>)': HTTP status 400 (message: "schema violation (paths.1: should start with: /)")
```

This is due to [a breaking change in Kong 3.x](https://github.com/Kong/kong/blob/3.0.0/CHANGELOG.md#core)
```
Kong will no longer use an heuristic to guess whether a route.path is a regex pattern. From now 3.0 onwards, all regex paths must start with the "~" prefix, and all paths that don't start with "~" will be considered plain text.
```

For now we're still using 2.8.x but would like to adopt `decK` specifically with the `openapi2kong` functionality. Would a flag to disable the autoprefixing of `~` [here](https://github.com/Kong/go-apiops/blob/eb265c35cd4832557a51c2e94b8aae9a83fa1b26/openapi2kong/openapi2kong.go#L885) be something you'd consider? Maybe generalized to something like `--kong-version` in case more changes are needed.

If you're not planning to support Kong < 3, might want to indicate Kong version compatibility in docs since this is in the `decK` docs.
> [decK is compatible with Kong Gateway (OSS) >= 1.x and Kong Enterprise >= 0.35.](https://docs.konghq.com/deck/1.27.x/#compatibility).

**Comment by Tieske** [comment]
Yep, good call. It indeed only supports Kong 3.x. Will add to the docs.

As a workaround, have you tried converting the output from 3.x to 2.x using `deck convert` ?

**Comment by Tieske** [comment]
hmmm, seems we can only do 2.x to 3.x, that's a bummer.

**Comment by danielpoonwj** [comment]
> hmmm, seems we can only do 2.x to 3.x, that's a bummer.

yup `deck convert --from 'kong-gateway-3.x' --to 'kong-gateway-2.x'` throws this error, it's [not an allowed combination](https://github.com/Kong/deck/blob/v1.27.1/convert/convert.go#L68-L97).
```
Error: converting file: cannot convert from 'kong-gateway-3.x' to 'kong-gateway-2.x' format
```

i managed to do a dirty workaround by manually stripping the `~` prefix though.

1. generate the deck state in JSON
```bash
deck file openapi2kong --format json
```

2. manipulate with `jq`
```bash
jq '.services[].routes[].paths[] |= ltrimstr("~")'
```

I would've liked to work in yaml but `yq` doesn't support `ltrimstr` even though [the issue](https://github.com/mikefarah/yq/issues/87) is closed as completed (??).

**Comment by Tieske** [comment]
thanks for replying with a possible workaround!

**Comment by rustyjux** [comment]
@danielpoonwj I think `yq eval '(.services[].routes[].paths[]) |= sub("^~"; "")'` would do the same thing as `ltrimstr`, at least in this relatively limited context?
